var date = new Date()
console.log(date.toString())
console.log(date.toTimeString())
console.log(date.toLocaleString())
console.log(date.getFullYear())
console.log(date.getMonth())
console.log(date.getDate())
console.log(date.getMinutes())